version: 2

builds:
  - binary: nigopdf
    ldflags:
      - -s -w -X github.com/wadoyoka/nigopdf/cmd.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

homebrew_casks:
  - name: nigopdf
    binaries:
      - nigopdf
    repository:
      owner: wadoyoka
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/wadoyoka/nigopdf"
    description: "A PDF toolkit - merge and split PDF files"
