version: 2

builds:
  - binary: pdf-join
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

homebrew_casks:
  - name: pdf-join
    binaries:
      - pdf-join
    repository:
      owner: wadoyoka
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/wadoyoka/pdf-join-go"
    description: "Merge PDF files in a directory"
