version: 2

builds:
  - binary: pdf-join
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

brews:
  - repository:
      owner: wadoyoka
      name: homebrew-tap
    name: pdf-join
    homepage: "https://github.com/wadoyoka/pdf-join-go"
    description: "Merge PDF files in a directory"
    license: "MIT"
    install: |
      bin.install "pdf-join"
    test: |
      system "#{bin}/pdf-join", "--help"
